# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: $(dotNetVersion)
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build Application'

- task: UseDotNet@2
  displayName: 'Pack nuget package'

- script: dotnet pack --configuration $(buildConfiguration)

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '67eaf4d2-2360-43e9-957e-1c7d67049d36/88b6b86e-cb24-4bc3-9ccf-a657edd961fa'